### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by jtoufik** [ArexanK/the-web-is-for-everyone-interactive-functionality#3]
Misschien is het handiger om de font aan te houden die Oba momenteel al gebruikt "Avenir", Ik zie dat je hier nogal een grote sprong maakt van andere font.

<img width="564" alt="Scherm­afbeelding 2023-03-31 om 11 05 59" src="https://user-images.githubusercontent.com/112856590/229077493-74d222a0-a3c5-4fba-8135-c6ff4aa7602a.png">

**Comment by ArexanK** [comment]
thanks ga ik doen
